In [477]:
from IPython.display import display, HTML
from datetime import datetime

# Notebook title
Notebook_title = "Back to Basics"

# Current date
current_date = datetime.now().strftime("%B %d, %Y")

# Create the HTML string with title, date, and author
html_content = f"""
<h1 style="text-align:center;">{Notebook_title}: Python</h1>
<br/>
<h3 style="text-align:left;">MikiasHWT</h3>
<h3 style="text-align:left;">{current_date}</h3>
"""

# Display the HTML content in the output
display(HTML(html_content))

# Prep Workplace

In [478]:
import numpy as np
print("Numpy version:", np.__version__)
np?

# To show multiple lines in output
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

Numpy version: 2.1.2


Type:        module
String form: <module 'numpy' from 'c:\\Users\\Owner\\Documents\\GitHub\\PythonDataScienceHandbook\\.venv\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\owner\documents\github\pythondatasciencehandbook\.venv\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as 

In [479]:
######################## Git/venv/Python Good practices: ########################
# Save package requirements as txt file using pip freeze. 
# Exclude .venv from git repo (i will choose to include it in .gitignore for now)
# Include session_info.show() at end of scripts

# pip freeze > requirements.txt (to save)
# pip install -r requirements.txt (to install)
# pip install session_info 

# Data Types

## Primitive data-types
Int, Float, Bool, String

### Integer

In [480]:
# Integer
type(-12)

int

### Double

In [481]:
# Double
type(12.5)

float

### Complex

In [482]:
# Complex
type(3j)

complex

### Boolean

In [483]:
# Boolean
type(False)
type(True)
type("False")
type("True")

bool

bool

str

str

### String

In [484]:
String1='First String' # Single quotes
String2="Second String" # Double quotes

In [485]:
# Strings
type(String1) 
type(String2)


str

str

In [486]:
# Repeat
String1*2

'First StringFirst String'

In [487]:
# Index
String1[0]

'F'

In [488]:
# Slice
String1[:3]

'Fir'

In [489]:
# Range Slice
String1[0:5]

'First'

In [490]:
# Concatenate
String1 + " & " + String2


'First String & Second String'

In [491]:
# Slice and concatenate
String1[0:5] + " & " + String2[0:6]

'First & Second'

In [492]:
# Proper capitalization
str.capitalize('string')

'String'

In [493]:
# Length
len(String1)

12

In [494]:
# Determine if digits
String1.isdigit()

False

In [495]:
String3="12345"
String3.isdigit()

True

In [496]:
# Strings are immutable, but new string can be made from combinations
String4= String1.replace('First', String3)
String1
String3
String4

'First String'

'12345'

'12345 String'

In [497]:
# to search for a substring within a string and return the index of the first occurrence of the substring. 
# If the substring is not found, it returns -1.
String1.find(String3)

-1

In [498]:
# Value of String3 is found starting at index [0] of String 4
String4.find(String3)

0

In [499]:
# Value of String 5 is found starting at index [6] of String 4
String5="String"
String4.find(String5)

6

In [500]:
# Data type conversion 

# TypeError: can only concatenate str (not "int") to str

# x = 2
# y = "Part "
# combo = (y) + (x)
# combo

In [501]:
# Data type conversion
x = 2
y = "Part "
combo = (y) + str(x)
combo

'Part 2'

In [502]:
# Tripple quotes
multiline="""
Multiline text
between tripple quotes 
is also
an acceptable 
string type
"""

In [503]:
multiline

'\nMultiline text\nbetween tripple quotes \nis also\nan acceptable \nstring type\n'

In [504]:
type(multiline)

str

## Non-Primitive
List, Array, Tuple, Set, Dictionary, Stacks, Queue, Graphs, Trees, Files

### Lists
- An ordered, mutable collection of items, 
  - e.g., [1, 2, 3, "apple"]

In [505]:
# Lists
num_list=[1,2,3]

In [506]:
type(num_list)

list

In [507]:
char_list=["First Name", "Middle Name", "Last Name"]

In [508]:
type(char_list)

list

In [509]:
mix_list=["First", 10, 3j, ["Internal", "List"], "Last", 20, ]

In [510]:
type(mix_list)

list

In [511]:
# Lists can be indexed (and nested)
mix_list[3]

['Internal', 'List']

In [512]:
# Lists can be appended
mix_list.append("New Addition")

In [513]:
mix_list

['First', 10, 3j, ['Internal', 'List'], 'Last', 20, 'New Addition']

In [514]:
# Lists can be edited
mix_list[5]=200000

In [515]:
mix_list

['First', 10, 3j, ['Internal', 'List'], 'Last', 200000, 'New Addition']

### Array
-Not used often
-Similar to lists, with some differences. 
-Require specific module (import array as arr)

- common type codes used with array:

    - 'b': Signed char (1 byte)
    - 'B': Unsigned char (1 byte)
    - 'u': Unicode character (2 or 4 bytes, depending on the platform)
    - 'h': Signed short (2 bytes)
    - 'H': Unsigned short (2 bytes)
    - 'i': Signed int (2 or 4 bytes)
    - 'I': Unsigned int (2 or 4 bytes)
    - 'l': Signed long (4 bytes)
    - 'L': Unsigned long (4 bytes)
    - 'f': Float (4 bytes)
    - 'd': Double (8 bytes)

In [516]:
import array as arr

# datatype inside array [] requires specification with a code. 
a = arr.array("I",[3,6,9])
type(a)

array.array

In [517]:
# Define the array of Unicode characters
array_char = arr.array("u", ["c", "a", "t", "s"])

array_char

# index
array_char[1]



array('u', 'cats')

'a'

In [518]:
# Use tounicode() method to convert to a string
array_string = array_char.tounicode()

# Print the array as a string
print(array_string)  # Output: 'cats'

cats


In [519]:
# Numpy Arrays
np.array([1, 2, 44, 5, 6])

array([ 1,  2, 44,  5,  6])

In [520]:
# Specify data type
np.array([1, 2, 3], dtype = str)

array(['1', '2', '3'], dtype='<U1')

In [521]:
# multidimensional array
np.array([range(i, i+10) for i in [0, 5, 10]])

# Produces vectors as follows range(0, 10), range(5, 15), range(10, 20)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [522]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [523]:
# Create 3x5 array with floating-point arrays filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [524]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [525]:
# Create an array filled with a linear sequence 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [526]:
# Create an array filled with 5 values evenly spaced between 0 and 3
np.linspace(0, 3, 5)

array([0.  , 0.75, 1.5 , 2.25, 3.  ])

In [527]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

array([[0.66252687, 0.01357164, 0.6228461 ],
       [0.67365963, 0.971945  , 0.87819347],
       [0.50962438, 0.05571469, 0.45115921]])

In [528]:
# Create a 3x3 array of normally distributed random values with mean 0 and SD 1
np.random.normal(0, 1, (3, 3))

array([[-0.04411241, -0.36326702, -0.01234481],
       [ 0.04212149,  1.95929589, -0.1984257 ],
       [ 0.33053441, -1.43582841,  0.02752832]])

In [529]:
# create a 3x3 array of random integers in the interval of [0, 10]
np.random.randint(0, 10, (3, 3))

array([[9, 1, 4],
       [6, 8, 2],
       [3, 0, 0]], dtype=int32)

In [530]:
# Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [531]:
# Array attributes
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [532]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes") # size in bytes of each element
print("nbytes:", x3.nbytes, "bytes") # total size in bytes of the array
# nbytes = itemsize x size

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes


In [533]:
# Aggregating on arrays
M = np.random.random((3, 4))
print(M)

[[0.65279032 0.63505887 0.99529957 0.58185033]
 [0.41436859 0.4746975  0.6235101  0.33800761]
 [0.67475232 0.31720174 0.77834548 0.94957105]]


In [534]:
# Numpy defaults to aggregating the entire array
M.sum()

np.float64(7.435453494015987)

In [535]:
# Specify min value per column
M.min(axis=0)

array([0.41436859, 0.31720174, 0.6235101 , 0.33800761])

In [536]:
# Specify min value per row
M.min(axis=1)

array([0.58185033, 0.33800761, 0.31720174])

The ``axis`` keyword specifies the *dimension of the array that will be collapsed*, rather than the dimension that will be returned.
So specifying ``axis=0`` means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.

#### Other aggregation functions

Most aggregates have a ``NaN``-safe counterpart that computes the result while ignoring missing values,


|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |



#### Boolean Arrays and masks

when you write ``x < 3``, internally NumPy uses ``np.less(x, 3)``.
    A summary of the comparison operators and their equivalent ufunc is shown here:

| Operator	    | Equivalent ufunc    | 
|---------------|---------------------| 
|``==``         |``np.equal``         | 
|``<``          |``np.less``          | 
|``>``          |``np.greater``       | 
|``!=``         |``np.not_equal``     |
|``<=``         |``np.less_equal``    |
|``>=``         |``np.greater_equal`` |

In [537]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [538]:
# Boolean array mask
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [539]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [540]:
# Equivalent 
np.sum(x < 6)

np.int64(8)

In [541]:
# Benefits of sum(): it can be performed across rows or columns
# How many values less than 6 in each row
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [542]:
# are there any values greater than 8?
np.any(x > 8)

np.True_

In [543]:
# are there all values equal to 6?
np.all(x == 6)

np.False_

In [544]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

Warning: Python has built-in ``sum()``, ``any()``, and ``all()`` functions. These have a different syntax than the NumPy versions, and in particular will fail or produce unintended results when used on multidimensional arrays. Use ``np.sum()``, ``np.any()``, and ``np.all()`` for mutlidimensional arrays. 

In [545]:
# Select values that return True (as 1-D array)
x[x < 5]

array([0, 3, 3, 3, 2, 4], dtype=int32)

The difference between the keywords ``and`` and ``or``, and the operators ``&`` and ``|`` is this:

 ``and`` and ``or`` gauge the truth or falsehood of *entire object*
 
 while ``&`` and ``|`` refer to *bits within each object*.

When you use ``and`` or ``or``, it's equivalent to asking Python to treat the object as a single Boolean entity.
In Python, all nonzero integers will evaluate as True. Thus:

In [546]:
bool(42), bool(0)

(True, False)

In [547]:
bool(42 and 0)

False

In [548]:
bool(42 or 0)

True

when using ``&`` and ``|`` on integers, the expression operates on the bits of the element, applying the *and* or the *or* to the individual bits making up the number:

In [549]:
bin(42)

'0b101010'

In [550]:
bin(59)

'0b111011'

In [551]:
bin(42 & 59)

'0b101010'

In [552]:
bin(42 | 59)

'0b111011'

When you have an array of Boolean values in NumPy, this can be thought of as a string of bits where ``1 = True`` and ``0 = False``, and the result of ``&`` and ``|`` operates similarly to above:

In [553]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

array([ True,  True,  True, False,  True,  True])

Using ``or`` on these arrays will try to evaluate the truth or falsehood of the entire array object, which is not a well-defined value:

In [554]:
# A or B 
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Similarly, when doing a Boolean expression on a given array, you should use ``|`` or ``&`` rather than ``or`` or ``and``:

In [555]:
x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

In [556]:
# (x > 4) and (x < 8)
# ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### Boolean bitwise logic operators

| Operator	    | Equivalent ufunc    |
|---------------|---------------------|
|``&``          |``np.bitwise_and``   |
|``^``          |``np.bitwise_xor``   |
|&#124;         |``np.bitwise_or``    |
|``~``          |``np.bitwise_not``   |

#### Sorting Arrays

In [557]:
# returning a sorted version of an array without modifying the input
x = np.array([2, 1, 3, 5, 4])
np.sort(x)
x

array([1, 2, 3, 4, 5])

array([2, 1, 3, 5, 4])

In [558]:
# sort an array in place 
x.sort()
x

array([1, 2, 3, 4, 5])

In [559]:
# return indices of sorted elements
x = np.array([2, 1, 3, 5, 4])
i = np.argsort(x)
i

# fancy indexing to can then be used to return sorted array
x[i]

array([1, 0, 2, 4, 3])

array([1, 2, 3, 4, 5])

In [560]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [561]:
# sort each column of X
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [562]:
# sort each row of X
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

In [563]:
# Partial sorting: Partitioning 
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([1, 2, 3, 4, 5, 6, 7])

 ``np.partition`` takes an array and a number *K*; the result is a new array with the smallest *K* values to the left of the partition, and the remaining values to the right, in arbitrary order:

#### Structured Arrays

In [564]:
# use compound data types for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 
                          'formats':('U10', 'i4', 'f8')})

print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


``'U10'`` = "Unicode string of maximum length 10," 

``'i4'`` = "4-byte (i.e., 32 bit) integer," 

``'f8'`` = "8-byte (i.e., 64 bit) float."

In [565]:
# define data values
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [566]:
# fill structured data array
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [567]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [568]:
# Get first row of data
data[0]

np.void(('Alice', 25, 55.0), dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

### Tuples
- An ordered, immutable collection of items, 
  - e.g., (1, 2, 3, "apple")

In [569]:
# Tuples
tpl =(1,2,3,3,4,5,5)

In [570]:
type(tpl)

tuple

In [571]:
# Tuple can be indexed
tpl[2]

3

In [572]:
# Tuples cannot be modified

# TypeError: 'tuple' object does not support item assignment

# tpl[2]=12

In [573]:
# Tuples cannot be appended

# AttributeError: 'tuple' object has no attribute 'append'

# tpl.append("12")

### Sets
- An unordered, mutable collection of unique items, 
  - e.g., {1, 2, 3}

In [574]:
# Sets
a_set={44,1,3,3,2,44}

In [575]:
type(a_set)

set

In [576]:
# Sets dont output duplicate elements
a_set

{1, 2, 3, 44}

In [577]:
# Sets cannot be indexed

# TypeError: 'set' object is not subscriptable

# a_set[3]

In [578]:
# Sets cannot be modified 

# TypeError: 'set' object does not support item assignment

# a_set[3]=126

In [579]:
# Sets cannot be appended

# AttributeError: 'set' object has no attribute 'append'

# a_set.append(5)

In [580]:
# Use case: sets
set1={1,25,4,57,6,7,7,83,22}
set2={7,6,1,65,78,23,84,22}

In [581]:
# UNION: all unique elements from both sets
set1 | set2

{1, 4, 6, 7, 22, 23, 25, 57, 65, 78, 83, 84}

In [582]:
# INTERSECTION: only the elements that are common to both sets
set1 & set2

{1, 6, 7, 22}

In [583]:
# DIFFERENCE: the elements that are in set1 but not in set2
set1 -  set2

{4, 25, 57, 83}

In [584]:
# SYMMETRIC DIFFERENCE: elements that are in either set1 or set2 but not in both
set1 ^ set2

{4, 23, 25, 57, 65, 78, 83, 84}

In [585]:
# SUBSET: Checks if all elements of one set are contained in another set. (includes the possibility that they are the same sets)
set1 <= set2
set1.issubset(set2)

False

False

In [586]:
# PROPER SUBSET: Checks if one set is a strict subset of another (but the sets are not equal).
set1 < set2  # True if set1 is a proper subset of set2.

False

In [587]:
# SUPERSET: Checks if one set contains all elements of another set. (includes the possibility that they are the same sets)
set1 >= set2
set1.issuperset(set2)

False

False

In [588]:
# PROPER SUPERSET: Checks if one set is a strict superset of another (but the sets are not equal).
set1 > set2  # True if set1 is a proper superset of set2.

False

In [589]:
# DISJOING SET: Checks if two sets have no elements in common
set1.isdisjoint(set2) # Returns True if set1 and set2 have no elements in common.

False

### Dictionary
- A collection of key-value pairs, 
  - e.g., {"name": "Alice", "age": 25}.

In [590]:
# Dictionary : require key-value pair
dict={"First Name":"Mikias", "Username":"MikiasHWT", "Birthplace":"Eritrea", "Favorite Food":["Tsebhi", "Shiro", "Qulwa", "Pizza"]}

In [591]:
dict

{'First Name': 'Mikias',
 'Username': 'MikiasHWT',
 'Birthplace': 'Eritrea',
 'Favorite Food': ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza']}

In [592]:
type(dict)

dict

In [593]:
# Dictionary keys can be called
dict.keys()

dict_keys(['First Name', 'Username', 'Birthplace', 'Favorite Food'])

In [594]:
# Dictionary values can be called
dict.values()

dict_values(['Mikias', 'MikiasHWT', 'Eritrea', ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza']])

In [595]:
# Dictionary items (combination of key,value) can be called
dict.items()

dict_items([('First Name', 'Mikias'), ('Username', 'MikiasHWT'), ('Birthplace', 'Eritrea'), ('Favorite Food', ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza'])])

In [596]:
# Values can be indexed by specifying key
dict["First Name"]

'Mikias'

In [597]:
# Specific values can be modified
dict["Birthplace"] = "Asmara, Eritrea"

In [598]:
dict

{'First Name': 'Mikias',
 'Username': 'MikiasHWT',
 'Birthplace': 'Asmara, Eritrea',
 'Favorite Food': ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza']}

In [599]:
# Dict can be further modified and appended (without deleting existing key:values)
dict.update({'First Name': 'Mikias',
 'Birthplace': 'Asmara, Eritrea aka: The Motherland',
 'Favorite Food': ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza'], 
 "Weight Gained":"Non-Negligable"})

In [600]:
dict

{'First Name': 'Mikias',
 'Username': 'MikiasHWT',
 'Birthplace': 'Asmara, Eritrea aka: The Motherland',
 'Favorite Food': ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza'],
 'Weight Gained': 'Non-Negligable'}

In [601]:
# Key:Value pairs can also be deleted
del dict["Weight Gained"]

In [602]:
dict

{'First Name': 'Mikias',
 'Username': 'MikiasHWT',
 'Birthplace': 'Asmara, Eritrea aka: The Motherland',
 'Favorite Food': ['Tsebhi', 'Shiro', 'Qulwa', 'Pizza']}

### Stacks : TBL
- a linear data structure that follows the LIFO (Last In, First Out) principle.
- Elements are added and removed from the top of the stack.
Common operations include:
    - Push: Adding an element to the top.
    - Pop: Removing the top element.
    - Peek: Viewing the top element without removing it.
- Example: Managing browser history or undo operations in text editors.
- stacks can be implemented using lists or the collections.deque module.

### Queue : TBL
- a linear data structure that follows the FIFO (First In, First Out) principle.
- Elements are added at the rear and removed from the front.
Common operations include:
    - Enqueue: Adding an element to the rear.
    - Dequeue: Removing an element from the front.
- Example: Handling tasks in a printer queue or CPU scheduling.
- queues can be implemented using lists, collections.deque, or the queue module

### Graphs : TBL
- a non-linear data structure consisting of nodes (vertices) and edges (connections between nodes).
- Graphs can be:
    - Directed: Edges have a direction (one-way).
    - Undirected: Edges have no direction (two-way).
    - Weighted: Edges have weights (costs) associated with them.
- Graphs are used to model relationships and are widely used in networking, social media, and pathfinding algorithms (e.g., shortest path problems)
- graphs can be implemented using dictionaries or external libraries like NetworkX.

### Trees : TBL
- a hierarchical data structure made of nodes
    - The top node is called the root.
    - Each node has children and one parent (except the root).
    - Nodes with no children are called leaves.
- Special types of trees include:
    - Binary Trees: Each node has at most two children (left and right).
    - Binary Search Trees (BST): A binary tree where the left child is smaller and the right child is larger than the parent.
    - AVL Trees and Red-Black Trees: Self-balancing binary search trees.
- Trees are used in many applications like parsing expressions, file systems, and databases.
- trees can be implemented using classes or using libraries like anytree

### File : TBL
- used for persistent data storage.
- A file contains data (text or binary) and is stored on a storage device.
- Common file operations include:
        - Read: Extracting data from a file.
        - Write: Writing data to a file.
        - Append: Adding data to the end of an existing file.
    Example: Reading or writing to a .txt, .csv, or .json file.
- file handling is done through built-in functions like open(), and more advanced file handling is possible with libraries like pandas for structured data

# Comparisons

## Logical Operators

In [603]:
# Equal
2 == 2 # True
2 == 3 # False

"Apples" == "Oranges" # False
"Apples" == "Apples" # True

True

False

False

True

In [604]:
# Double Negatives
not(2 == 2) # False
not(2 == 3) # True

not("Apples" == "Oranges") # True
not("Apples" == "Apples") # False

False

True

True

False

In [605]:
# AND logic
(2 == 2) and (2 == 3) # False
("Apples" == "Apples") and ("Oranges" == "Oranges") # True

False

True

In [606]:
# OR logic
(2 == 2) or (2 == 3) # True
(2 == 4) or (2 == 3) # False
("Apples" == "Apples") or ("Oranges" == "Oranges") # True


True

False

True

In [607]:
# Not Equal
2 != 2 # False
2 != 3 # True

"Apples" != "Oranges" # True
"Apples" != "Apples" # False

False

True

True

False

In [608]:
# Greater than 
2 > 3 # False
3 > 2 # True

"AAAA" > "BBB" # False (alphabet comparison)
len("AAAA") > len("BBB") # True

"C" > "BBB" # True 
len("C") > len("BBB") # False

False

True

False

True

True

False

In [609]:
# Greater than or equal to
2 >= 3 # False
3 >= 3 # True
4 >= 3 # True

False

True

True

In [610]:
# Less than 
2 < 3 # True
3 < 2 # False

True

False

In [611]:
# Less than or equal to
2 <= 3 # True
3 <= 3 # True
4 <= 3 # False

True

True

False

## Membership Operators

In [612]:
# In
Sentence="Apples are not the same as oranges."

"Apples" in Sentence # True
"." in Sentence # True
"apples" in Sentence # False (Case sensitive)
"Pears" in Sentence # False
"!" in Sentence # False

True

True

False

False

False

In [613]:
Numbers=[1,3,4,7,8]

1 in Numbers # True
2 in Numbers # False

True

False

In [614]:
# Not In
Sentence="Apples are not the same as oranges."

"Apples" not in Sentence # False
"." not in Sentence # True
"apples" not in Sentence # True (Case sensitive)
"Pears" not in Sentence # True
"!" not in Sentence # False

False

False

True

True

True

In [615]:
Numbers=[1,3,4,7,8]

1 not in Numbers # False
2 not in Numbers # True

False

True

# If Else
- conditional statements used for decision-making

![IF -> ELIF -> Else](img\python-if-elif-else.png)

In [616]:
if 20 > 10:
    print("20 is greater than 10")
else:
    print("Hmm...maybe its not")

20 is greater than 10


In [617]:
# Checking mutliple conditions. 
if (20 < 10) or (10 > 20):
    print("20 is less than 10")
else:
    print("BOOM, I knew it! 20 IS bigger than 10.")

BOOM, I knew it! 20 IS bigger than 10.


In [618]:
# Writing it in one line
print("It worked") if 10>20 else print("10 is not bigger than 20")

10 is not bigger than 20


In [619]:
# Nested statements
if (20 > 10) and (10 < 20):
    print("20 is greater than 10")
    if (20 > 9):
        print("Another victory for 20, which is greater than 9")
else:
    print("Hmm 20 taking some L's")

20 is greater than 10
Another victory for 20, which is greater than 9


# For Loops
- used to iterate over a sequence (such as a list, tuple, string, or range) and execute a block of code multiple times.

![For Loop](img\python-for-loop.png)

In [620]:
# Iterate over list
a_list=[1, 2, 3, 4, "apple", 3j]

for items in a_list:
    print(items)

1
2
3
4
apple
3j


In [621]:
# List items arent essential
for items in a_list:
    print("items")

items
items
items
items
items
items


In [622]:
# Their use can even get wierd
for items in a_list:
    print(items + items)

2
4
6
8
appleapple
6j


In [623]:
# Iterate over dictionary
hobbies={"sports":"soccer", "self-care":"Comedy", "educational":["Design", "Reading", "Coding"]}

# Call values
for things in hobbies.values():
    print(things)

soccer
Comedy
['Design', 'Reading', 'Coding']


In [624]:
# Call keys
for things in hobbies.keys():
    print(things)

sports
self-care
educational


In [625]:
# Call Key:Value pairs (must define them)
for category, hobby in hobbies.items():
    print(category, "->", hobby)

sports -> soccer
self-care -> Comedy
educational -> ['Design', 'Reading', 'Coding']


In [626]:
# Call Key:Value pairs (must define them, in order of Key:Value)
for Random, aaaaaaaa in hobbies.items():
    print(aaaaaaaa, "-%&%-", Random)

soccer -%&%- sports
Comedy -%&%- self-care
['Design', 'Reading', 'Coding'] -%&%- educational


In [627]:
# Nester for loops
Adjective=["blue", "small", "foreign"]
Noun=["shirt", "table", "pen"]
Verb=["smells", "eats", "walks"]

for adjs in Adjective:
    for nns in Noun:
        for vrbs in Verb:
            print("The", adjs, nns, vrbs, "and we love it.")


The blue shirt smells and we love it.
The blue shirt eats and we love it.
The blue shirt walks and we love it.
The blue table smells and we love it.
The blue table eats and we love it.
The blue table walks and we love it.
The blue pen smells and we love it.
The blue pen eats and we love it.
The blue pen walks and we love it.
The small shirt smells and we love it.
The small shirt eats and we love it.
The small shirt walks and we love it.
The small table smells and we love it.
The small table eats and we love it.
The small table walks and we love it.
The small pen smells and we love it.
The small pen eats and we love it.
The small pen walks and we love it.
The foreign shirt smells and we love it.
The foreign shirt eats and we love it.
The foreign shirt walks and we love it.
The foreign table smells and we love it.
The foreign table eats and we love it.
The foreign table walks and we love it.
The foreign pen smells and we love it.
The foreign pen eats and we love it.
The foreign pen walks

In [628]:
# The rules...need further consideration. 
Adjective=["blue", "small", "foreign"]
Noun=["shirt", "table", "pen"]
Verb=["smells", "eats", "walks"]

for nns in Noun:
    for nns in Noun:
        for vrbs in Verb:
            for adjs in Adjective:
                for adjs in Adjective:
                    print("The", nns, vrbs,"and we are confused.")



The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt smells and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt eats and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
The shirt walks and we are confused.
T

# While Loops
- repeatedly executes a block of code as long as a specified condition remains True

![While Loop](img\python-while-loop.png)

In [629]:
# Continues until the condition is not true
num=1

while num <= 10:
    print(num)
    num = num + 1
    

1
2
3
4
5
6
7
8
9
10


In [630]:
# Else statement
num=1

while num <= 10:
    print(num)
    if num == 11:
        break
    num = num + 1
else:
    print("Eleve... \nOops, were we supposed to stop at 10?")

1
2
3
4
5
6
7
8
9
10
Eleve... 
Oops, were we supposed to stop at 10?


In [631]:
# Continue statement ("continue" returns loop back to "while" when its condition is met. 
########### Creating an infinite loop)

# num=1

# while num <= 10:
#     print(num)
#     if num == 9:
#         continue
#     num = num + 1
# else:
#     print("This wont print with an infinite loop")

In [632]:
# Continue statement without infinite loop

num=1

while num <= 10:
    num = num + 1
    if num == 9:
        continue
    print(num)
else:
    print("We skipped #9 but included #11. \nBecause'continue' returns the loop to the 'while' conditional \nthereby subverting #9 output \nand enforcing #11 output")

2
3
4
5
6
7
8
10
11
We skipped #9 but included #11. 
Because'continue' returns the loop to the 'while' conditional 
thereby subverting #9 output 
and enforcing #11 output


# Functions
- a block of reusable code that performs a specific task
-  Functions can accept inputs called arguments or parameters, which allow you to pass values into the function.

In [633]:
# writing a useless function
def useless():
    print("We did it!")

# calling said useless function
useless()

We did it!


In [634]:
# Function definition with name arguments
def greet(name):
    return f"Hello, {name}!"

# Function call
print(greet("Mikias"))


Hello, Mikias!


In [635]:
# Squaring a number
def num_squared(num):
    print(num**2)

# Call it
num_squared(1)
num_squared(2)
num_squared(3)
num_squared(4)
num_squared(5)


1
4
9
16
25


In [636]:
# Multiple arguments
def num_raised_to(num, power):
    print(num**power)

# Call it
num_raised_to(2,0)
num_raised_to(2,1)
num_raised_to(2,2)
num_raised_to(2,3)

1
2
4
8


In [637]:
# keyword arguments for increased flexibility in calling arguments. 
def num_raised_to(num, power):
    print(num**power)

# Call it by specifying arguments. 
num_raised_to(power=0, num=2)
num_raised_to(num=2, power=1)
num_raised_to(power=2, num=2)
num_raised_to(num=2, power=3)

1
2
4
8


In [638]:
# Arbitrary number of arguments
def sum_numbers(*nums):
    total = sum(nums)  
    print(f"Sum of {nums} = {total}")

# Call the function with different numbers of arguments
sum_numbers(1, 2, 3)
sum_numbers(5, 10, 15, 20, 25)
sum_numbers(100, 200)

Sum of (1, 2, 3) = 6
Sum of (5, 10, 15, 20, 25) = 75
Sum of (100, 200) = 300


In [639]:
# To pass a list or tuple, they must be unpacked with '*'
def sum_numbers(*nums):
    total = sum(nums)  
    print(f"Sum of {nums} = {total}")

# Upack with * (or they will be treated as a single argument)
a_tuple = (1, 2, 3)
sum_numbers(*a_tuple)

a_list = [5, 10, 15]
sum_numbers(*a_list)

Sum of (1, 2, 3) = 6
Sum of (5, 10, 15) = 30


In [640]:
# Passing dictionaries (or DF's)
def display_info(**kwargs):
    print("Name:", kwargs['name'])
    print("Age:", kwargs['age'])  
    print("City:", kwargs['city'])

# Calling the function without the 'age' argument
display_info(name="John", age=30, city="Seattle")
print("")
display_info(name="Lisa", age=28, city="LA", state="California") # unspecified key:value pairs will get skipped

# Missing key:value pairs that are specified in function will throw an error
# display_info(name="Mike", city="New York")



Name: John
Age: 30
City: Seattle

Name: Lisa
Age: 28
City: LA


In [641]:
# Functions and for loops
def create_profile(**info):
    for key, value in info.items():
        print(f"{key}: {value}")

# Call the function with different sets of keyword arguments (no errors)
create_profile(name="John", age=30, profession="Engineer")
print()
create_profile(name="Alice", age=25, location="New York", hobby="Photography", pet="Dog")
print()
create_profile(name="Mike", city="New York")

name: John
age: 30
profession: Engineer

name: Alice
age: 25
location: New York
hobby: Photography
pet: Dog

name: Mike
city: New York


In [642]:
# Passing a Dataframe into function (requires unpacking with **)
data = {
    'name': ['John', 'Alice', 'Bob'],
    'age': [25, 30, 22],
    'city': ['Seattle', 'New York', 'Los Angeles'],
    'profession': ['Engineer', 'Designer', 'Writer']
}

df = pd.DataFrame(data)

# Function to create a personal profile using **kwargs
def create_profile(**info):
    for key, value in info.items():
        print(f"{key}: {value}")
    print()  # blank line

# Loop through the DataFrame rows and pass each row to the function (unpacking it into dictionaries per person)
for index, row in df.iterrows():
    create_profile(**row)

name: John
age: 25
city: Seattle
profession: Engineer

name: Alice
age: 30
city: New York
profession: Designer

name: Bob
age: 22
city: Los Angeles
profession: Writer



# List Comprehension
- a concise and efficient way to create lists. (better than for loops)

Basic syntax

```python
[expression for item in iterable if condition]
```

- Expression: This is the value or operation that forms the elements of the new list.
- Item: Represents each element in the iterable (like in a loop).
- Iterable: This is the sequence or collection you're iterating over (like a list, range, etc.).
- If condition: (Optional) This is a filtering condition that allows you to include only certain elements.


In [643]:
# Traditional For Loop
numbers = [1, 2, 3, 4, 5]
squares = []

for num in numbers:
    squares.append(num ** 2)
print(squares)

[1, 4, 9, 16, 25]


In [644]:
# Using list comprehension
numbers = [1, 2, 3, 4, 5]

squares = [num ** 2 for num in numbers]

print(squares)


[1, 4, 9, 16, 25]


# Converting Data Types

## Converting Primitives

In [645]:
# define integer
num_int=7
type(num_int)

# define string
num_str="7"
type(num_str)

int

str

In [646]:
# TypeError: unsupported operand type(s) for +: 'int' and 'str'

# num_int + num_str

In [647]:
# Converting from string to integer 
convert_num=int(num_str)
type(convert_num)

convert_num + num_int

int

14

In [648]:
# Converting from integer to string
convert_str=str(num_int)
type(convert_str)

convert_str + num_str

str

'77'

## Converting Non-Primitives

In [649]:
# define list
a_list=[1,2,3]
type(a_list)

# define tuple
a_tuple=(1,2,3)
type(a_tuple)

list

tuple

In [650]:
# Converting list -> tuple
convert_tuple=tuple(a_list)
type(convert_tuple)

tuple

In [651]:
# Converting tuple -> list
convert_list=list(a_tuple)
type(convert_list)

list

In [652]:
# Convert list -> set
another_list=[1,2,2,2,3,3]
convert_set=set(another_list)
type(convert_set)

# But sets only retain unique values
convert_set

set

{1, 2, 3}

In [653]:
# Converting dictionary
dict_type={"name":"Mikias", "username":"MikiasHWT", "Age":"31"}
type(dict_type)

dict_type.keys()
dict_type.values()
dict_type.items()

dict

dict_keys(['name', 'username', 'Age'])

dict_values(['Mikias', 'MikiasHWT', '31'])

dict_items([('name', 'Mikias'), ('username', 'MikiasHWT'), ('Age', '31')])

In [654]:
# Converting portions of dictionary to lists
print("___________________keys -> lists______________________")
convert_keys=list(dict_type.keys())
type(convert_keys)
convert_keys
convert_keys[0]
convert_keys[1]
convert_keys[2]

print("__________________values -> lists_____________________")

convert_vals=list(dict_type.values())
type(convert_vals)
convert_vals
convert_vals[0]
convert_vals[1]
convert_vals[2]

print("__________________items -> lists______________________")

convert_items=list(dict_type.items())
type(convert_items)
convert_items
convert_items[0]
convert_items[1]
convert_items[2]

___________________keys -> lists______________________


list

['name', 'username', 'Age']

'name'

'username'

'Age'

__________________values -> lists_____________________


list

['Mikias', 'MikiasHWT', '31']

'Mikias'

'MikiasHWT'

'31'

__________________items -> lists______________________


list

[('name', 'Mikias'), ('username', 'MikiasHWT'), ('Age', '31')]

('name', 'Mikias')

('username', 'MikiasHWT')

('Age', '31')

In [655]:
# Long strong -> lists (essentially parsing a sentence)
sentence="My name is Mikias and I am currently 31 years old"
sentence_list=list(sentence)
type(sentence_list)
sentence_list[:17]

list

['M',
 'y',
 ' ',
 'n',
 'a',
 'm',
 'e',
 ' ',
 'i',
 's',
 ' ',
 'M',
 'i',
 'k',
 'i',
 'a',
 's']

# Pandas

In [656]:
import pandas as pd
pd.__version__
pd?

'2.2.3'

Type:        module
String form: <module 'pandas' from 'c:\\Users\\Owner\\Documents\\GitHub\\PythonDataScienceHandbook\\.venv\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\owner\documents\github\pythondatasciencehandbook\.venv\lib\site-packages\pandas\__init__.py
Docstring:  
pandas - a powerful data analysis and manipulation library for Python

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating poi

## Pandas Series
A Pandas ``Series`` is a one-dimensional array of indexed data.

In [700]:
# Creatinga a pandas series
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

The ``Series`` wraps both a sequence of values and a sequence of indices, which can be accessed with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [701]:
# values
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [702]:
# Indices 
data.index

RangeIndex(start=0, stop=4, step=1)

In [703]:
# indexing returns associated value
data[1]

np.float64(0.5)

In [704]:
# slicing
data[1:3]

1    0.50
2    0.75
dtype: float64

Numpy Array has an *implicitly defined* integer index used to access the values

the Pandas ``Series`` has an *explicitly defined* index associated with the values.

This gives the ``Series`` object additional capabilities. ie: the index need not be an integer, but can consist of values of any desired type such as strings. 

In [742]:
# Series as generalized NumPy array
data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                 index=['one', 'two', 'three', 'four'])

data

one      0.25
two      0.50
three    0.75
four     1.00
dtype: float64

In [743]:
# indexing
data["one"]

np.float64(0.25)

In [744]:
# list items
list(data.items())

[('one', 0.25), ('two', 0.5), ('three', 0.75), ('four', 1.0)]

In [745]:
# append
data['five'] = 1.25

data

one      0.25
two      0.50
three    0.75
four     1.00
five     1.25
dtype: float64

In [746]:
# slicing by explicit index (final index included)
data['two':'four']

two      0.50
three    0.75
four     1.00
dtype: float64

In [747]:
# slicing by implicit integer index (final index excluded)
data[0:2]

one    0.25
two    0.50
dtype: float64

In [748]:
# masking
data[(data > 0.3) & (data < 0.8)]

two      0.50
three    0.75
dtype: float64

In [708]:
# Non sequential data
data = pd.Series([0.25, 0.5, 0.75, 1.0], 
                 index=[2, 5, 3, 7])

data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [709]:
data[5]

np.float64(0.5)

the ``loc`` attribute allows indexing and slicing that always references the explicit index:

In [750]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

'a'

In [753]:
# Explicit indexing 
data.loc[1]

data.loc[1:3]

'a'

1    a
3    b
dtype: object

The ``iloc`` attribute allows indexing and slicing that always references the implicit Python-style index:

In [754]:
# Implicit indexing
data.iloc[1]

data.iloc[1:3]

'b'

3    b
5    c
dtype: object

A dictionary is a structure that maps arbitrary keys to a set of arbitrary values

``Series`` is a structure which maps typed keys to a set of typed values.

This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [712]:
# Dictrionary to Series
population_dict = {'California': 38332521, 
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population = pd.Series(population_dict)

population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [713]:
# indexing like dicts
population["California"]

np.int64(38332521)

In [716]:
# slicing like array (inclusive)
population["Texas":"Illinois"]

Texas       26448193
New York    19651127
Florida     19552860
Illinois    12882135
dtype: int64

In [717]:
# default intex is integer sequence
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [718]:
# data can a scalar set to repeat
pd.Series(5, index=["first", "second", "third"])

first     5
second    5
third     5
dtype: int64

In [722]:
# data can be a dict, where index defailt to dict keys
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [723]:
# populate only with specified index vales
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

## Dataframe
the ``DataFrame`` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.

If a ``Series`` is an analog of a one-dimensional array with flexible indices, 

a ``DataFrame`` is an analog of a two-dimensional array with both flexible row indices and flexible column names.

Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects.
"aligned" meaning that they share the same index.

In [729]:
# Construct a Series 
area_dict = {'California':423967, 'Texas': 695662, 'New York': 141297, 
             'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)

area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [725]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}

population = pd.Series(population_dict)

population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [730]:
# Combine both Series with a dictionairy
states = pd.DataFrame({'population': population, 
                      'area': area})

states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [731]:
# index labels
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [732]:
# column attribute is an index of column labels
states.columns

Index(['population', 'area'], dtype='object')

think of a ``DataFrame`` as a specialization of a dictionary.
Where a dictionary maps a key to a value, a ``DataFrame`` maps a column name to a ``Series`` of column data.

asking for ``area`` attribute returns the ``Series`` object containing the areas data

In [757]:
# indexing
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [756]:
# dot notation
states.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [759]:
states.area is states['area']

True

In [761]:
# appending with new column
states['density'] = states['population'] / states['area']

states

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [762]:
# Dataframe as 2-D array
states.values

array([[3.83325210e+07, 4.23967000e+05, 9.04139261e+01],
       [2.64481930e+07, 6.95662000e+05, 3.80187404e+01],
       [1.96511270e+07, 1.41297000e+05, 1.39076746e+02],
       [1.95528600e+07, 1.70312000e+05, 1.14806121e+02],
       [1.28821350e+07, 1.49995000e+05, 8.58837628e+01]])

In [764]:
# Transpose 
states.T

California         Texas      New York       Florida  \
population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
population  1.288214e+07  
area        1.499950e+05  
density     8.588376e+01

population    area     density
California    38332521  423967   90.413926
Texas         26448193  695662   38.018740
New York      19651127  141297  139.076746
Florida       19552860  170312  114.806121
Illinois      12882135  149995   85.883763

In [734]:
# constructing a dataframe
pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [735]:
# Dataframe from 2-dimensional NumPy array
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])

foo       bar
a  0.662527  0.013572
b  0.622846  0.673660
c  0.971945  0.878193

In [737]:
# Dataframe from structured array 
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])

A

pd.DataFrame(A)

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [766]:
# Create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'Score': [85, 90, 95, 100]}

df = pd.DataFrame(data, index=['A', 'B', 'C', 'D'])

print("DataFrame:")
print(df)

DataFrame:
      Name  Age  Score
A    Alice   25     85
B      Bob   30     90
C  Charlie   35     95
D    David   40    100


## Index Based Selection

iloc : Selecting data based on its numerical position in the data.

In [767]:
# Access 2nd elements of all columns
df.iloc[1]

Name     Bob
Age       30
Score     90
Name: B, dtype: object

In [768]:
# Access specific value using row at index 1 and column at index 
df.iloc[1, 2]

np.int64(90)

In [769]:
# to retrive a column
df.iloc[:, 0]

A      Alice
B        Bob
C    Charlie
D      David
Name: Name, dtype: object

## Label-based selection

loc : selects from the data index value, not its position. 

In [775]:
df.loc[:, 'Age']

A    25
B    30
C    35
D    40
Name: Age, dtype: int64

## Manipulating DF's

In [662]:
# Setting index
df_new = df.set_index("Name")

print("New DataFrame:")
print(df_new)

New DataFrame:
         Age  Score
Name               
Alice     25     85
Bob       30     90
Charlie   35     95
David     40    100


In [663]:
# Conditional selection
df.Age == 30

A    False
B     True
C    False
D    False
Name: Age, dtype: bool

In [664]:
# Conditional subsetting
df.loc[df.Age == 30]

Name  Age  Score
B  Bob   30     90

In [665]:
# Conditional subsetting with logical operators 
# and = &
# or = |
# is in = isin()
df.loc[(df.Age >= 35) & (df.Score >= 100)]

Name  Age  Score
D  David   40    100

In [666]:
# Assigning data
df["Tried Hard"] = "Yes"

df

Name  Age  Score Tried Hard
A    Alice   25     85        Yes
B      Bob   30     90        Yes
C  Charlie   35     95        Yes
D    David   40    100        Yes

## Summaries and maps

In [667]:
df

Name  Age  Score Tried Hard
A    Alice   25     85        Yes
B      Bob   30     90        Yes
C  Charlie   35     95        Yes
D    David   40    100        Yes

### Summaries

In [668]:
# Common stats for numerical variables
df.describe()

Age       Score
count   4.000000    4.000000
mean   32.500000   92.500000
std     6.454972    6.454972
min    25.000000   85.000000
25%    28.750000   88.750000
50%    32.500000   92.500000
75%    36.250000   96.250000
max    40.000000  100.000000

In [669]:
# Descibe for categoricals
df["Tried Hard"].describe()

count       4
unique      1
top       Yes
freq        4
Name: Tried Hard, dtype: object

In [670]:
# mean
df.Score.mean()

np.float64(92.5)

In [671]:
# Unique values
df.Score.unique()

array([ 85,  90,  95, 100])

In [672]:
# Count number of instances of a given value
df.Score.value_counts()

Score
85     1
90     1
95     1
100    1
Name: count, dtype: int64

The following table lists Python operators and their equivalent Pandas object methods:

| Python Operator | Pandas Method(s)                      |
|-----------------|---------------------------------------|
| ``+``           | ``add()``                             |
| ``-``           | ``sub()``, ``subtract()``             |
| ``*``           | ``mul()``, ``multiply()``             |
| ``/``           | ``truediv()``, ``div()``, ``divide()``|
| ``//``          | ``floordiv()``                        |
| ``%``           | ``mod()``                             |
| ``**``          | ``pow()``                             |


### Maps

a function that takes one set of values and "maps" them to another set of values.

In [673]:
# Mean centering using map()
# Store mean value
Score_mean_value = df.Score.mean()

# Apply lambda function to shift the mean
# takes each individual n value in score columns and subtracts the mean
df["Centered_scores"] = df.Score.map(lambda n: n - Score_mean_value)

df


Name  Age  Score Tried Hard  Centered_scores
A    Alice   25     85        Yes             -7.5
B      Bob   30     90        Yes             -2.5
C  Charlie   35     95        Yes              2.5
D    David   40    100        Yes              7.5

### Apply
the apply function is a powerful tool used to apply a function along an axis of a DataFrame (rows or columns) or to a Series. It provides flexibility in applying custom functions to manipulate data.
How it Works:

    For a Series:
        You can use apply to apply a function to each element of a Series.

    For a DataFrame:
        You can specify whether to apply the function along the columns (axis=0) or rows (axis=1).

The apply function is often used for data transformations, computations, or even generating new columns based on existing data.

In [674]:
# Using apply with a Series

# Create a Series
s = pd.Series([1, 2, 3, 4])

# Apply a lambda function to square each element
squared = s.apply(lambda x: x ** 2)

print(squared)

0     1
1     4
2     9
3    16
dtype: int64


In [675]:
# Using apply on a DataFrame (Column-wise)

# Create a DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# Apply a function along columns (axis=0 by default)
column_sums = df.apply(sum)

print(column_sums)

A     6
B    15
C    24
dtype: int64


In [676]:
# Using apply on a DataFrame (Row-wise)

# Apply a function along rows (axis=1)
row_sums = df.apply(lambda row: row.sum(), axis=1)

print(row_sums)

0    12
1    15
2    18
dtype: int64


In [677]:
# Applying a Custom Function

# Custom function to calculate the range (max - min) of values
def calc_range(row):
    return row.max() - row.min()

# Apply the custom function along rows
row_ranges = df.apply(calc_range, axis=1)

print(row_ranges)

0    6
1    6
2    6
dtype: int64


## Grouping and Sorting

### Grouping

In [678]:
# Create a DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'C', 'B', 'A', 'C'],
        'Values': [10, 20, 30, 40, 50, 60, 30, 20, 10, 20]}

df = pd.DataFrame(data)

df

Category  Values
0        A      10
1        B      20
2        A      30
3        B      40
4        A      50
5        B      60
6        C      30
7        B      20
8        A      10
9        C      20

In [679]:
# Group by 'Category' and count instances
grouped = df.groupby('Category').count()

print(grouped)

# Group by Values and count instances
df.groupby('Values').Category.count()

          Values
Category        
A              4
B              4
C              2


Values
10    2
20    3
30    2
40    1
50    1
60    1
Name: Category, dtype: int64

In [680]:
# Group by 'Category' and apply multiple aggregation functions
grouped = df.groupby('Category').agg(['mean', 'sum', 'max'])

print(grouped)

         Values         
           mean  sum max
Category                
A          25.0  100  50
B          35.0  140  60
C          25.0   50  30


In [681]:
# Grouping by Multiple Columns

# Create a more complex DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A', 'B'],
        'SubCategory': ['X', 'X', 'Y', 'Y', 'Y', 'X'],
        'Values': [10, 20, 30, 40, 50, 60]}

df = pd.DataFrame(data)

# Group by both 'Category' and 'SubCategory'
grouped = df.groupby(['Category', 'SubCategory']).sum()

print(grouped)

                      Values
Category SubCategory        
A        X                10
         Y                80
B        X                80
         Y                40


In [682]:
# Applying Custom Functions to Groups

# Custom function to calculate the range (max - min)
def calc_range(x):
    return x.max() - x.min()

# Apply the custom function to each group
grouped = df.groupby('Category')['Values'].apply(calc_range)

print(grouped)

Category
A    40
B    40
Name: Values, dtype: int64


In [683]:
# Filtering Groups

df.groupby('Category').sum()

# Filter groups where the sum of 'Values' is greater than 100
filtered = df.groupby('Category').filter(lambda x: x['Values'].sum() > 100)

print(filtered)

SubCategory  Values
Category                    
A                XYY      90
B                XYX     120

  Category SubCategory  Values
1        B           X      20
3        B           Y      40
5        B           X      60


In [684]:
# Transforming Groups

# Subtract the group mean from each value
df['Centered'] = df.groupby('Category')['Values'].transform(lambda x: x - x.mean())

print(df)

  Category SubCategory  Values  Centered
0        A           X      10     -20.0
1        B           X      20     -20.0
2        A           Y      30       0.0
3        B           Y      40       0.0
4        A           Y      50      20.0
5        B           X      60      20.0


### Multi-Indexing

A MultiIndex is like having multiple levels of row or column labels. It's useful when dealing with high-dimensional data or data that is hierarchically structured

In [685]:
# Creating a MultiIndex from a DataFrame

# Create a DataFrame
data = {'Category': ['A', 'A', 'B', 'B'],
        'SubCategory': ['X', 'Y', 'X', 'Y'],
        'Values': [10, 20, 30, 40]}

df = pd.DataFrame(data)

# Set 'Category' and 'SubCategory' as MultiIndex
df.set_index(['Category', 'SubCategory'], inplace=True)

type(df)

print(df)

pandas.core.frame.DataFrame

                      Values
Category SubCategory        
A        X                10
         Y                20
B        X                30
         Y                40


In [686]:
# Accessing Data in a MultiIndex DataFrame

# Access data for Category 'A' and SubCategory 'X'
value = df.loc[('A', 'X')]

print(value)

Values    10
Name: (A, X), dtype: int64


In [687]:
# Slice through different levels of the index.

# Access all data for Category 'A'
a_data = df.loc['A']

print(a_data)

             Values
SubCategory        
X                10
Y                20


In [688]:
# Create a DataFrame
data = {'Category': ['A', 'A', 'B', 'B'],
        'SubCategory': ['X', 'Y', 'X', 'Y'],
        'Values': [10, 20, 30, 40],
        'Amount': [100, 150, 200, 250]}

df = pd.DataFrame(data)

df.set_index(['Category', 'SubCategory'], inplace=True)

print(df)

df = pd.DataFrame(data)

# Stacking and Unstacking a MultiIndex (which converts columns to row levels or vice versa.)
# Unstack the 'SubCategory' index level
unstacked = df.set_index(['Category', 'SubCategory']).unstack()

print("\n", unstacked)

# Stack the unstacked DataFrame
stacked = unstacked.stack()

print("\n", stacked)

                      Values  Amount
Category SubCategory                
A        X                10     100
         Y                20     150
B        X                30     200
         Y                40     250

             Values     Amount     
SubCategory      X   Y      X    Y
Category                          
A               10  20    100  150
B               30  40    200  250

                       Values  Amount
Category SubCategory                
A        X                10     100
         Y                20     150
B        X                30     200
         Y                40     250


C:\Users\Owner\AppData\Local\Temp\ipykernel_4812\2599008885.py:22: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  stacked = unstacked.stack()


In [689]:
# Swap the levels of the MultiIndex
swapped = df.set_index(['Category', 'SubCategory']).swaplevel()

print(swapped)

                      Values  Amount
SubCategory Category                
X           A             10     100
Y           A             20     150
X           B             30     200
Y           B             40     250


In [690]:
# Reset the index
reset_df = df.set_index(['Category', 'SubCategory']).reset_index()

print(reset_df)

  Category SubCategory  Values  Amount
0        A           X      10     100
1        A           Y      20     150
2        B           X      30     200
3        B           Y      40     250


### Sorting

`sort_index()`: Sorts the DataFrame/Series by its index (row or column labels).

`sort_values()`: Sorts the DataFrame/Series by the values in one or more columns.

In [691]:
# Sorting a DataFrame by Row Index

# Create a DataFrame
data = {'Category': ['B', 'A', 'C', 'A', 'B', 'C', 'A', 'C'],
        'Values': [30, 20, 40, 10, 12, 20, 30, 40]}

df = pd.DataFrame(data, index=[3, 2, 4, 1, 5, 7, 6, 8])

# Sort by row index
sorted_df = df.sort_index()

print(df)
print("\n", sorted_df)

  Category  Values
3        B      30
2        A      20
4        C      40
1        A      10
5        B      12
7        C      20
6        A      30
8        C      40

   Category  Values
1        A      10
2        A      20
3        B      30
4        C      40
5        B      12
6        A      30
7        C      20
8        C      40


In [692]:
data = {
    'D': ['dog', 'cat', 'bird'],
    'B': [15, 10, 5],
    'A': [3.5, 4.1, 2.9],
    'C': [True, False, True]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Sort the columns by their labels
sorted_columns = df.sort_index(axis=1)
print("\nAxis 1 index sorted DataFrame:")
print(sorted_columns)

Original DataFrame:
      D   B    A      C
0   dog  15  3.5   True
1   cat  10  4.1  False
2  bird   5  2.9   True

Axis 1 index sorted DataFrame:
     A   B      C     D
0  3.5  15   True   dog
1  4.1  10  False   cat
2  2.9   5   True  bird


In [693]:
# sort_values()

# Create a DataFrame
data = {'Category': ['B', 'A', 'C', 'A', 'B', 'C', 'A', 'C'],
        'Values': [30, 20, 40, 10, 12, 20, 30, 40]}

df = pd.DataFrame(data, index=[3, 2, 4, 1, 5, 7, 6, 8])

# Sorting a DataFrame by Values
# Sort by the 'Values' column
sorted_by_values = df.sort_values(by='Values')

print(sorted_by_values)

  Category  Values
1        A      10
5        B      12
7        C      20
2        A      20
6        A      30
3        B      30
4        C      40
8        C      40


In [694]:
# Sorting by Multiple Columns

# Sort by 'Category' and then 'Values'
sorted_by_multiple = df.sort_values(by=['Category', 'Values'])

print(sorted_by_multiple)

  Category  Values
1        A      10
2        A      20
6        A      30
5        B      12
3        B      30
7        C      20
4        C      40
8        C      40


In [695]:
# Sorting in Descending Order
# Sort by 'Values' in descending order
sorted_descending = df.sort_values(by='Values', ascending=False)

print(sorted_descending)

  Category  Values
4        C      40
8        C      40
6        A      30
3        B      30
7        C      20
2        A      20
5        B      12
1        A      10


In [696]:
# Sorting with NaN Values
# Create a DataFrame with NaN values
data_with_nan = {'Category': ['B', 'A', 'C', None],
                 'Values': [30, None, 40, 10]}

df_with_nan = pd.DataFrame(data_with_nan)

# Sort by 'Values' with NaN values placed first
sorted_nan_first = df_with_nan.sort_values(by='Values', na_position='first')

print(sorted_nan_first)

  Category  Values
1        A     NaN
3     None    10.0
0        B    30.0
2        C    40.0


# End

In [697]:
# Replace spaces in notebook title with underscores
filename = Notebook_title.replace(" ", "_") + "_requirements.txt"

# Run the pip freeze command and save the output txt file
!pip freeze > $filename

In [699]:
import session_info
session_info.show()

ModuleNotFoundError: No module named 'session_info'